### PR TITLE
250 enable doi creation admin

### PR DESCRIPTION
**Pull request by sorochak**
## Description:

This pull request introduces an enhancement to the DOI generation feature by transitioning from hardcoded Datacite prefix and authentication credentials to a dynamic system managed through the  Admin Dashboard by storing credentials in the Firebase database. This change addresses a need for flexibility and security in managing Datacite credentials, enabling administrators to easily update these credentials without the need for direct code modifications.

## Key Features and Improvements:

* Dynamic Datacite Credentials Management: Updated the Firestore database schema to store `dataciteCredentials` securely. This includes fields for the prefix and authHash, allowing for dynamic retrieval based on the user's region.

* Admin Dashboard Enhancements: introduced new fields for managing Datacite credentials directly from the Admin Dashboard. This update includes the ability to enable/disable DOI creation, add, and delete Datacite credentials.

* Security: Updated Firebase database rules to restrict access to `dataciteCredentials` exclusively to admins of their respective organization. This required a restructuring of the rules and database schema.

* Codebase Improvements: Removed the hardcoded `datacitePrefix` from `regions.js`. A separate issue has been opened to suggest further migration of configuration data into the database.

* Updated DOI Generation Logic: Updated the DOI generation logic to fetch the `datacitePrefix` from the database instead of relying on hardcoded values. 

* Testing: Added unit testing for all new functions.

* Documentation Update: Added a new section in the README to guide administrators and maintainers on managing and deploying Firebase Security Rules, promoting consistency for future maintenance and updates.

### To Do:
Once these changes are approved and merged...
- [x] Update the production database to include the new structural schema changes
- [x] deploy updated security rules to production database
- [ ] Add Datacite credentials via Admin dashboard for Hakai, IYS, and any other organization that requires DOI creation

### CODE REVIEW

**Comment by sorochak** [comment]
[The Firebase best practices](https://firebase.google.com/docs/database/web/structure-data#flatten_data_structures) for data structure recommend avoiding nesting data and to use flattened data structures (denormalized). 

[Firebase security rules](https://firebase.google.com/docs/rules/insecure-rules) cascade through the structure, with rules at shallow parent paths override rules at deeper child nodes. When you write a rule at a child node, it can only grant additional privileges. YOU CAN’T REFINE OR REVOKE ACCESS TO DATA AT A DEEPER PATH IN THE DATABASE.

The cioos-metadata-form db structure has `region` at the top and everything else stored in deeper child nodes. We need everyone to be able to see/read all the regions. This becomes a problem when we want to add a child node for each region to store `dataciteCredentials` and need to restrict read/write access to those to admins of the region.

In order to achieve the revoking of read privileges to child nodes we need to restructure a bit. We will create a sibling node to `regions` called `regionsAdmin` and all the admin nodes will fall under it (`projects` , `permissions`, `reviewers`,) and we’ll add the new node `dataciteCredentials`. read access to those will be limited to admins of the region. All logged in users should be able to read `projects`.

**Comment by sorochak** [comment]
Exported the prod DB and imported it into the dev DB so dev is up to date with prod - hakai projects is now populated in dev as it is in prod.

**Comment by sorochak** [comment]
While thinking on how best to structure the UI for the 'Enable DOI Creation' part of the Admin Dashboard, I came across the following example that I like (screenshot below). 

I think that implementing something similar to the example for the rest of the Admin dashboard (projects, admins, reviewers) might provide an improved experience and could look neater.

s_14B4BD8EDBFA59296DCDB812AB5C6EF8CE164AAF0A2268A9E90E57893E23504E_1627245829693_Screenshot+101

**Comment by sorochak** [comment]
To Do:

Encryption and Security:
- [x] setup firebase db rules to restrict `dataciteCredentials` access to admins for the specified region
- [x] generate authHash before storing in the db
        Cloud Functions lets you run Realtime Database operations with full administrative privileges,
- [x] if you choose to define or edit your security rules using the Firebase console, make sure that you also update the rules defined in your project directory `.rules` (from the docs)

Firestore schema and db update things:
- [x] Update Firestore Schema: in the current structure of the realtime database the top node beneath root is `region`. Beneath `region` we can add a child node `dataciteCredentials` which can store `prefix` and `authHash`. (note: this should happen automatically when the below functions are called)

in the utils file, similar to `firebaseRecordFunctions.js` and `firebaseContactFunctions.js`:
- [x] implement functions to add new and update or delete existing `dataciteCredentials` based on the `region`
- [x] remove `datacitePrefix` field from `regions.js`
- [x] open new issue suggesting moving regions object from `regions.js` to the database

Modifying the Admin Dashboard
- [x] refactor `Admin.jsx` from class based component to functional component to modernize the React codebase
- [x] add forms and fields in the admin dashboard to input the prefix and Datacite Credentials 
- [x] add enable/disable DOI creation checkbox
- [x] add delete functionality to remove datacite credentials
- [x] include validation to ensure the data is in the correct format.
- [x] update IdentificationTab to get datacitePrefix from database rather than from the regions file
- [x] remove conditional render in IdentificationTab that checks for a `datacitePrefix`
- [x] Render the DOI creation/update/delete buttons based on a field that is set in the Admin Dashboard

Updating Firebase Functions:
- [x]  modify the existing firebase functions to query for the `dataciteCredentials` based on the region involved in the current operation.

Testing:
- [x] write unit tests for the new functions and components created, focusing on the ability to add, update, and delete credentials, as well as the correct retrieval and use of the credentials in the firebase functions

Documentation:
- [x] Add section in README on `Manage and deploy Firebase Security Rules`

**Comment by fostermh** [comment]
possible bug:
- when I go to https://cioos-metadata-form--pr318-250-enable-doi-creat-7sm1ghe6.web.app/#/en/hakai/admin the 'enbable doi creation' is not checked even though the dataciteHash and prefix fields have values in the database.
- The current rules on the dev database do not allow you to see the admin page, and thus update projects, unless you are an admin. previously you were allowed to update projects if you were a reviewer

**Comment by sorochak** [comment]
@fostermh I believe the 'enbable doi creation' bug should be fixed and have updated the regionAdmin rules to allow reviewers read access to the admin page.

**Comment by Br-Johnson** [comment]
Not sure I'm the best one to review this PR. It seems mostly related to backend rather than user experience, no? Let me know if there's specific feedback you need.

**Comment by sorochak** [comment]
@Br-Johnson I added you and @timvdstap to this PR so you'll be aware of the changes to the Admin dashboard. Notably the need/ability to store Datacite credentials and enable DOI generation for organizations via the Admin dashboard.

**Comment by Br-Johnson** [comment]
Ah, OK got it. So that this can be extended to CIOOS etc...

**Comment by sorochak** [comment]
Right. If other organizations want/require the ability to generate DOIs via the form, an administrator for that organization will be able to enable that feature by entering their Datacite credentials in the Admin dashboard. Instead of requiring one of the developers to modify code files.

**Comment by Br-Johnson** [comment]
Cool. It looks great to me, thanks for letting us know!

**Review by fostermh — APPROVED** [review]
we merging make sure to update existing database and hakai credentials in production db

**Pull request merged**
