### PR TITLE
Contacts page updates

### LINKED ISSUE #172: Discrepancy between citation preview in form vs. result in CKAN
From what I can infer the citation preview in the metadata intake form shows the year the data was published, whereas in CKAN the citation year is based on the revised date (if it exists).

### LINKED ISSUE #184: Bug: role - Publisher
It appears that if I select "Publisher" as the single role for a contact, it still appears in the CKAN recommended citation (not in the citation preview in the metadata entry tool). 

edit: It might be that contacts that are assigned "Resource Provider" also show up in the CKAN citation.

### LINKED ISSUE #188: Let user pick which contacts appear in citation
Currently a contact appears in the citation only if it matches a certain role (Eg Owner/Author). To make it simpler/more clear, We can add a checkbox on the record's contact page to indicate whether it should appear in the citation.

Citation contacts will appear in 
`/mdb:MD_Metadata/mdb:identificationInfo/mri:MD_DataIdentification/mri:citation/cit:CI_Citation/cit:citedResponsibleParty`

Contacts that the user haven't checked would appear in:
`<mdb:contact>`

This would require a change to http://github.com/cioos-siooc/metadata-xml/ as well

### LINKED ISSUE #189: Separate first name, last name fields in contacts
There are some issues with automatically parsing a full name into "lastname, firstname" in the citation. For example, when there's a space in the last name it leads to a citation with only part of the last name.

Eg: Vincent van Gogh should read in a citation as "van Gogh, V." instead of "Gogh, V."

We can provide separate last name and first names fields and then in the XML they would be combined with a comma.

The ISO XML would change from this:

```xml
<cit:name>
     <gco:CharacterString>Vincent van Gogh</gco:CharacterString>
</cit:name>
```

To this:

```xml
<cit:name>
     <gco:CharacterString>van Gogh, Vincent</gco:CharacterString>
</cit:name>
```

And then CKAN would see the comma in the name and then be able to parse the full last name

### PR DESCRIPTION
**Pull request by n-a-t-e**
This PR adds
 - "Appear in citation" button, so that the contacts only appear in the citation if they are explicitly set that way
 - Separate first name and last names into two fields, to help with citation generation

Resolves #189
Resolves #188
Resolves #172
Resolves #184

### CODE REVIEW

**Review by sjbruce — COMMENTED** [review]
Updating contact information in the metadata form itself goes fine, the first name/last name rendering has a minor cosmetic bug were it doesn't show the last character struck in the list of contacts, but the actual contact information is correct when you select one and everything seems to save properly.

When updating the text field for Given or Last Name in the Contacts page I get the following error:

```
TypeError: updateContact is not a function
onChange
C:/Users/sbruce/Documents/GitHub/metadata-entry-form/src/components/FormComponents/ContactEditor.jsx:171

  168 | }
  169 | error={!givenNamesValid}
  170 | onChange={(a) => {
> 171 |   updateContact("indName")(
      | ^  172 |     `${value.givenNames  } ${  value.lastName}`
  173 |   );
  174 |   updateContactEvent("givenNames")(a);

handleChange
C:/Users/sbruce/Documents/GitHub/metadata-entry-form/node_modules/@material-ui/core/esm/InputBase/InputBase.js:367
callCallback
C:/Users/sbruce/Documents/GitHub/metadata-entry-form/node_modules/react-dom/cjs/react-dom.development.js:188
invokeGuardedCallbackDev
C:/Users/sbruce/Documents/GitHub/metadata-entry-form/node_modules/react-dom/cjs/react-dom.development.js:237
invokeGuardedCallback
C:/Users/sbruce/Documents/GitHub/metadata-entry-form/node_modules/react-dom/cjs/react-dom.development.js:292
invokeGuardedCallbackAndCatchFirstError
C:/Users/sbruce/Documents/GitHub/metadata-entry-form/node_modules/react-dom/cjs/react-dom.development.js:306
executeDispatch
C:/Users/sbruce/Documents/GitHub/metadata-entry-form/node_modules/react-dom/cjs/react-dom.development.js:389
executeDispatchesInOrder
C:/Users/sbruce/Documents/GitHub/metadata-entry-form/node_modules/react-dom/cjs/react-dom.development.js:414
executeDispatchesAndRelease
C:/Users/sbruce/Documents/GitHub/metadata-entry-form/node_modules/react-dom/cjs/react-dom.development.js:3278
executeDispatchesAndReleaseTopLevel
C:/Users/sbruce/Documents/GitHub/metadata-entry-form/node_modules/react-dom/cjs/react-dom.development.js:3287
forEachAccumulated
C:/Users/sbruce/Documents/GitHub/metadata-entry-form/node_modules/react-dom/cjs/react-dom.development.js:3257
runEventsInBatch
C:/Users/sbruce/Documents/GitHub/metadata-entry-form/node_modules/react-dom/cjs/react-dom.development.js:3304
runExtractedPluginEventsInBatch
C:/Users/sbruce/Documents/GitHub/metadata-entry-form/node_modules/react-dom/cjs/react-dom.development.js:3514
handleTopLevel
C:/Users/sbruce/Documents/GitHub/metadata-entry-form/node_modules/react-dom/cjs/react-dom.development.js:3558
batchedEventUpdates$1
C:/Users/sbruce/Documents/GitHub/metadata-entry-form/node_modules/react-dom/cjs/react-dom.development.js:21871
batchedEventUpdates
C:/Users/sbruce/Documents/GitHub/metadata-entry-form/node_modules/react-dom/cjs/react-dom.development.js:795
dispatchEventForLegacyPluginEventSystem
C:/Users/sbruce/Documents/GitHub/metadata-entry-form/node_modules/react-dom/cjs/react-dom.development.js:3568
attemptToDispatchEvent
C:/Users/sbruce/Documents/GitHub/metadata-entry-form/node_modules/react-dom/cjs/react-dom.development.js:4267
dispatchEvent
C:/Users/sbruce/Documents/GitHub/metadata-entry-form/node_modules/react-dom/cjs/react-dom.development.js:4189
unstable_runWithPriority
C:/Users/sbruce/Documents/GitHub/metadata-entry-form/node_modules/scheduler/cjs/scheduler.development.js:653
runWithPriority$1
C:/Users/sbruce/Documents/GitHub/metadata-entry-form/node_modules/react-dom/cjs/react-dom.development.js:11039
discreteUpdates$1
C:/Users/sbruce/Documents/GitHub/metadata-entry-form/node_modules/react-dom/cjs/react-dom.development.js:21887
discreteUpdates
C:/Users/sbruce/Documents/GitHub/metadata-entry-form/node_modules/react-dom/cjs/react-dom.development.js:806
dispatchDiscreteEvent
C:/Users/sbruce/Documents/GitHub/metadata-entry-form/node_modules/react-dom/cjs/react-dom.development.js:4168
```

**Comment by n-a-t-e** [comment]
ok I think I fixed that issue, let me know if you see anything else

**Review by sjbruce — COMMENTED** [review]
Contacts page now functions properly and the results in the pages and most downloads are consistent.

The EML for OBIS IPT download has some inconsistencies with how the names are displayed VS the other options, at least when it comes to situations where more than 1 space is in the given or surname fields.

For example: The "Maritimes Region Ecosystem Survey Rosette Vertical Profiles" dataset has names for departments like BIO and MEDS VS a person like Lindsay Beazley

```
<creator>
<individualName>
<givenName>Beazley</givenName>
<surName>Lindsay</surName>
</individualName>
...
</creator>
<metadataProvider>
<individualName>
<givenName>Services</givenName>
<surName>BIO</surName>
</individualName>
...
</metadataProvider>
}
<creator>
<individualName>
<givenName>(MEDS)</givenName>
<surName>Marine</surName>
</individualName>
...
</creator>
```

**Comment by n-a-t-e** [comment]
I made a few updates to this PR, let me know if you see anything else.  In that specific BIO record they put an organization name in the individual field, so that won't have a good outcome but that's to be expected.

**Pull request merged**
