### PR TITLE
add taxa tab for selecting taxa from GBIF

### PR DESCRIPTION
**Pull request by fostermh**
the taxa selection could be incorporated into another tab but I started with it here for simplicity of isolation.

The EML field `Sampling Extent` is comprised of geographic extent, temporal extent, and taxonomic extent. This last part was previously not captured in the form. If we want to populate this we will need a way to lookup taxa. The GBIF api seemed like a good option. The form does not currently allow manually filling a field out. I don't know if that is an issue or not. This PR is intended to start the discussion.

### CODE REVIEW

**Comment by timvdstap** [comment]
Hey Matt, thanks for starting this discussion. I think the main reason why it wasn't included initially is because while `Sampling Event` is a required field, it is free-text in the IPT. Taxonomic coverage is a section/field in the IPT as well but not required, and from earlier conversations I had with folks in this field it's not consistently populated. 

From my understanding, the PR to include fields for biological data in the metadata intake form included `Study Extent` as a free-text. Considering this, as well as how infrequent the taxonomic coverage is documented by data providers in the IPT, I'm not sure how beneficial adding a separate tab (or field) for this information is in the metadata form? Happy to hear the thoughts of others of course, as well I will inquire about the use of taxonomic coverage by others.

**Comment by fostermh** [comment]
https://eml.ecoinformatics.org/schema/eml-methods_xsd#MethodsType_MethodsType_sampling_studyExtent

If we think we should not include taxa in the sampling extent then I don't see us needing a box for this in the form at all. we can just concatenate geographic extent and temporal extent.

**Comment by timvdstap** [comment]
I think key to studyExtent is that it should also reflect the sampling frequency, and I was having a hard time finding the right ISO terms for that (see: https://github.com/cioos-siooc/metadata-entry-form/issues/277).

**Comment by fostermh** [comment]
so when I read the EML spec. the description of the `studyExtent` does mention sampling frequency
```
summary: A description of the geographic area sampled
                  (geographic coverage), the sampling frequency (temporal
                  coverage), and living organisms sampled (taxonomic
                  coverage.
```

However it seems to indicate that it is mapped to `temporal coverage`. When I read the spec for that field it appears to be a single date or rang of dates, much like the temporal extent of our existing records. Its true that we do not capture sampling frequency specifically in the iso metadata currently. The best fit for this would seem to be https://wiki.esipfed.org/MD_MaintenanceInformation where scope is set to something like `fieldSession` and 
mmi:maintenanceAndUpdateFrequency is set to something resonable

**Comment by timvdstap** [comment]
Brought it up to the group, seems like taxonomic coverage isn't currently used often by data providers, but that it's a great way to further future-proof the work through richer metadata, and is structured context that can be used when pulled by metadata harvesters. Apparently within the IPT there's an option to infer this information from the data tables, so I guess there's really no reason not to include it (and I should definitely start using it more frequently myself moving forward...). I'll let others chime in as well. @sjbruce Thoughts on including taxonomic extent?

**Comment by sjbruce** [comment]
> Brought it up to the group, seems like taxonomic coverage isn't currently used often by data providers, but that it's a great way to further future-proof the work through richer metadata, and is structured context that can be used when pulled by metadata harvesters. Apparently within the IPT there's an option to infer this information from the data tables, so I guess there's really no reason not to include it (and I should definitely start using it more frequently myself moving forward...). I'll let others chime in as well. @sjbruce Thoughts on including taxonomic extent?

Well, your comment about future-proofing the work and the potential benefits of richer metadata seem reason alone to include a capability like this for users looking to generate EML.  I mean, that's a selling point right there isn't it?  Especially if this lets the IPT and other services infer or make better use of the metadata.

The GBIF API returns many results using the suggest service, with lots of keys to be potentially leveraged by other GBIF services.  Looks like you could go crazy with this if desired.

There's a number of filters that can be applied to the suggest (and other services) that could probably be applied to narrow down or filter out undesirable results.

In terms of its own tab, it certainly seems like it could live with other biodiversity-specific data.

**Comment by fostermh** [comment]
Part of the linage PR is to merge the biodiversity tab into the other fields. so far I think I have worked out how to capture everything on the biodiversity tab with existing fields except taxa. The question of 'sampling frequency' is also still open. So... the Taxa tab could become the new biodiversity tab. That would make sens to me and we can add 'sampling frequency' if it turns out to be needed.

**Pull request merged**
