### PR TITLE
select resource type on start page

### PR DESCRIPTION
**Pull request by sorochak**
This PR solves issue https://github.com/cioos-siooc/metadata-entry-form/issues/264

So far all that's been done is the addition of radio buttons on the start page allowing users to select 'Resource Type' from three options, 'Oceanographic', 'Biological', 'Model'. The selection updates the `record` object with the field `resourceType`.

### CODE REVIEW

**Comment by sorochak** [comment]
The [issue](https://github.com/cioos-siooc/metadata-entry-form/issues/264) mentions that this depends on https://github.com/cioos-siooc/metadata-entry-form/issues/240. These changes have yet to be merged. 

I had a question regarding what do we want to happen when a resource type is selected. This may be sorted by merging PRs associated with issue 240?

There were also comments on selecting what language to be used (ie. 'Resource type' etc).

**Comment by Br-Johnson** [comment]
I feel like this touches on a number of open questions...

1) Do we wan't the form to be adaptive depending on what resource type is selected? Eg:
- include EOVs or not, 
- include EML fields or not, 
- require lineage if Model is selected... Couple of options there...

2) Is this idea for this selection to fill out MD_metadataScope>resourceScope? I see that's being set in the [Lineage PR](https://github.com/cioos-siooc/metadata-entry-form/pull/241)

**Comment by fostermh** [comment]
The intention with this would be to select the type of record we are filling out, not necessarily the resource type field. for example, we might select a biological type which would hide/show some fields but still select 'dataset' as the resource type

**Comment by sorochak** [comment]
> we might select a biological type which would hide/show some fields but still select 'dataset' as the resource type

I guess this is where the 'resource type' wording confusion comes in...

**Comment by fostermh** [comment]
replaced by https://github.com/cioos-siooc/metadata-entry-form/pull/322

**Pull request closed without merging**
