### PR TITLE
Add lineage section

### PR DESCRIPTION
**Pull request by fostermh**
https://github.com/cioos-siooc/metadata-entry-form/issues/240

### CODE REVIEW

**Comment by fostermh** [comment]
I think the issues is that firebase is passing arrays as objects to the client. Then only the first level of keys in a record are converted from objects to arrays. I added a recursive function to walk the record tree and convert objects as needed. It's working on my local, could you test on yours please?

**Comment by sjbruce** [comment]
Good news/bad news

Good News is that the lineage section now loads after the fact and the data is appropriately represented in the record.

Bad News is that it appears to break some other firebase connectivity - within the record things are fine, if I move back out to the menus on the left ("My Records" for example) - I get the following, is that happening on your end?

```
TypeError: 0 is read-only
./src/utils/misc.js/objectToArray/obj</<
C:/Users/sbruce/Documents/GitHub/metadata-entry-form/src/utils/misc.js:13

  10 | if (typeof obj === "object" && Object.keys(obj)[0] === "0") {
  11 |   obj = Object.entries(obj).map(([, v]) => {
  12 |     Object.keys(v).forEach((key) => {
> 13 |       v[key] = objectToArray(v[key]);
  14 | ^   })
  15 |     return v
  16 |   })
```

**Comment by sjbruce** [comment]
I was able to add multiple lineage objects and all that seems fine but any primary menu that queries the metadata records for a list generates the above error.

Admin & Contacts section are fine but the rest trigger the error.

**Comment by fostermh** [comment]
ok, I think I have it this time...

**Comment by n-a-t-e** [comment]
This looks great. I think we need more descriptions everywhere of what fields are for. At least "Authority" and "Code" could use an example. And a general intro to what Lineage is would be nice

Otherwise there's a minor UI glitch that could be fixed 

Screen Shot 2023-11-21 at 1 18 56 PM

**Comment by fostermh** [comment]
sorry, missed your comment nate, I add some text and look into the spacing issue. thanks for reviewing

**Comment by sjbruce** [comment]
Found a minor typo - "statement" was basically missing an "e" - so I've replaced all those.

HOWEVER!  This does cause a breaking change with any records that were previously saved with lineage information because the key in Firebase was also spelled incorrectly.  Those fields will need to be deleted or eslse it will crash upon loading of the lineage tab.

As a quick-fix, upping the size of the additional documentation column from 3 to 4 prevents the UI bug Nate pointed out.  At the expense of available screen real estate.

**Comment by n-a-t-e** [comment]
_HOWEVER! This does cause a breaking change with any records that were previously saved with lineage information because the key in Firebase was also spelled incorrectly. Those fields will need to be deleted or eslse it will crash upon loading of the lineage tab._

Lineage only exists in this PR, right? So you and Matt could delete any records that cause crashing, probably just a few

**Comment by sjbruce** [comment]
For sure, we shouldn't need to worry about anything real - but I wanted to make sure others testing the PR were aware of that problem.

**Comment by Br-Johnson** [comment]
Might be good to review this together in real time @fostermh. I'm not sure I understand what the goal is of the lineage section.

**Comment by fostermh** [comment]
this came out of the 'add model metadata records' discussion. The metadata TT recommended adding this section so that we could capture metadata related to models and how they are created. It's a section that was on the list to add for some time but became more important when we focused on models.

**Comment by Br-Johnson** [comment]
A main takeaway for me after talking this through in real time is that 'Lineage' is all about how the dataset was created. Ie. what were the sources, how were the sources processed, what tools were used to do the processing.

Our 'Related Works' section has some overlap but is more about identifying new versions and subsetting/identifying the larger work a work came from. 

Related Works and Lineage section also identifies references and citations and that Related Works relationType could be mapped into Lineage sources...

Also, is Lineage are required section? I think no, but perhaps if the resourceType is identified as a model in the Data Identification section

**Comment by fostermh** [comment]
Lineage falls under 'mdb:resourceLineage' in the[ iso19115 standard ](https://wiki.esipfed.org/MD_Metadata) and is not indicated as required. The [CIOOS Profile v3](https://docs.google.com/spreadsheets/d/1sUEfZt1UWI0LUzAYdAVmT_-HDOFe4g81HCoRLB7A7NM/edit#gid=1361923433) indicates it is 'Recommended'. We can make it required if resource type is modal it desired. Perhaps a discussion topic for the Metadata TT.

**Comment by Br-Johnson** [comment]
It might make sense to not include sources in the lineage
section but rather only collect that information in the Related Works section to populate lineage sources and Datacite relation types at the same time.

**Comment by fostermh** [comment]
@fostermh to merge with https://github.com/cioos-siooc/metadata-entry-form/pull/284

**Comment by Br-Johnson** [comment]
@fostermh Just going through this now but noticed the netlify preview hasn't updated for a few commits :S

**Comment by Br-Johnson** [comment]
Just a couple of suggestions here:
* Can we include 'Scope' and translate that the Datacite resourceType for every metadata record instead of just in the lineage section?
* Maybe we could rename 'Additional Documentation' to 'Lineage Documentation' to make it clearer
* When would we require multiple Lineages? Seems like Lineage should just be limited to one for the primary resource/metadata record.
* Can combine ISO "Lineage Statement" with eml "Processing Step/Method"? They seem close enough.
* Lineage Sources could be mapped to DataCite relatedWorks with relationType 'isDerivedFrom'

**Comment by fostermh** [comment]
replaced by https://github.com/cioos-siooc/metadata-entry-form/pull/322

**Pull request closed without merging**
