### PR TITLE
Ensures data collection end date occurs after start date

### PR DESCRIPTION
**Pull request by rjbergerud**
Not sure if there's other places where this needs doing.  Addresses issue #100

### CODE REVIEW

**Review by n-a-t-e — CHANGES_REQUESTED** [review]
Thanks for the PR!! it seems like when `null` is used as a default value for `minDate`/`maxDate` it messed up the year picker. Unless that's just me. If this also happens to you, can you switch `null` to `undefined`? Seems to fix this 
Screen Shot 2021-05-04 at 10 48 54 AM

**Comment by rjbergerud** [comment]
Odd, I didn't get that behaviour, can't imagine it being browser-dependent?  Null values seemed to work as input for the value prop, wonder why it didn't work for dateEnd.

Were there any errors raised in the console when you got the blank picker?

**Comment by n-a-t-e** [comment]
I tried Chrome and Firefox, same behaviour.  Maybe its just me?? To reproduce - 
1. Create a new record
2. Go to Data ID section
3. Go to _What is the start date when data was first collected?_
4. Click calendar button
5. click on the year Screen Shot 2021-05-05 at 2 52 06 PM

**Comment by rjbergerud** [comment]
Oh, I didn't understand what you meant before by year picker.  Yeah, I get that too when I go back to using null.

**Pull request merged**
