### PR TITLE
make resource name optionally bilingual

### LINKED ISSUE #204: Metadata entry form fields for converting to French - Data and Resources section bilingual Names and Descriptions
This issue is in regard to the Data and Resources section that displays on CKAN but is populated from the metadata entries. Specifically the Names are in English only, but the Descriptions have both an English and French field. Currently if you click French, all of the content on the page translates except for this text in the Data and Resources section.

See the original issue raised on the CKAN repo, as a linked issue.
https://github.com/cioos-siooc/ckan/issues/166

**Describe the bug**
Data and Resources section in CKAN dataset page not translated into French when switching (remains in English).

### PR DESCRIPTION
**Pull request by n-a-t-e**
Fixes #204

### CODE REVIEW

**Review by sjbruce — COMMENTED** [review]
There seems to be an issue with dataset resources that have both languages specified when downloading them in ISO XML or YAML formats - the resource names look like they're dumping a character array.

Resources that only have the old name appear to render fine.

```
<cit:name>
<gco:CharacterString>
{'0': 'A', '1': 't', '2': 'l', '3': 'a', '4': 'n', '5': 't', '6': 'i', '7': 'c', '9': 'Z', '10': 'o', '11': 'n', '12': 'e', '14': 'M', '15': 'o', '16': 'n', '17': 'i', '18': 't', '19': 'o', '20': 'r', '21': 'i', '22': 'n', '23': 'g', '25': 'P', '26': 'r', '27': 'o', '28': 'g', '29': 'r', '30': 'a', '31': 'm', '33': '(', '34': 'A', '35': 'Z', '36': 'M', '37': 'P', '38': ')', 'en': 'AZMP Project Page', 'fr': 'Page du projet AZMP'}
</gco:CharacterString>
</cit:name>
```

**Comment by n-a-t-e** [comment]
Thanks for pointing this out. This will be resolved via a database migration, where all the current resource names will be put into the the English name field

**Comment by julieDionne** [comment]
Same comment as Scott, but for CKAN.
image

**Comment by n-a-t-e** [comment]
This should be fixed now, let me know if you have any issues with it

**Pull request merged**
